# Generated by Django 6.1 on 2026-08-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('barangay', models.CharField(max_length=255, null=True)),
                ('municipality', models.CharField(max_length=255, null=True)),
                ('supplier_tin', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
