# Generated by Django 6.1 on 2026-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_tin',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
