# Generated by Django 6.1 on 2026-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0004_supplier_created_by_supplier_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
