# Generated by Django 6.1 on 2026-08-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0005_alter_department_dept_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
    ]
