# Generated by Django 6.1 on 2026-08-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0006_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
