# Generated by Django 6.1 on 2026-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0007_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='barangay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_tin',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
