# Generated by Django 6.1 on 2026-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0008_alter_employee_extension_alter_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_tin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
