# Generated by Django 6.1 on 2026-09-14 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0010_employee_contact_number_employee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('coa_id', models.AutoField(primary_key=True, serialize=False)),
                ('coa_code', models.CharField(max_length=20, unique=True)),
                ('coa_name', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], max_length=50)),
                ('is_posting_account', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coas_created', to=settings.AUTH_USER_MODEL)),
                ('parent_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_coas', to='mdsetup.chartofaccount')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coas_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
