# Generated by Django 6.1 on 2026-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdsetup', '0011_chartofaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
